#The disk space limit for computers and turtles, in bytes
computer_space_limit = 1000000
#The disk space limit for floppy disks, in bytes
floppy_space_limit = 125000
#Set how many files a computer can have open at the same time. Set to 0 for unlimited.
#Range: > 0
maximum_open_files = 128
#Set this to true to disable Lua 5.1 functions that will be removed in a future update. Useful for ensuring forward compatibility of your programs now.
disable_lua51_features = false
#A comma separated list of default system settings to set on new computers. Example: "shell.autocomplete=false,lua.autocomplete=false,edit.autocomplete=false" will disable all autocompletion
default_computer_settings = ""
#Enable Lua's debug library. This is sandboxed to each computer, so is generally safe to be used by players.
debug_enabled = true
#Log exceptions thrown by peripherals and other Lua objects.
#This makes it easier for mod authors to debug problems, but may result in log spam should people use buggy methods.
log_computer_errors = false

#Controls execution behaviour of computers. This is largely intended for fine-tuning servers, and generally shouldn't need to be touched
[execution]
	#The maximum time that can be spent executing tasks in a single tick, in milliseconds.
	#Note, we will quite possibly go over this limit, as there's no way to tell how long a will take - this aims to be the upper bound of the average time.
	#Range: > 1
	max_main_global_time = 10
	#Set the number of threads computers can run on. A higher number means more computers can run at once, but may induce lag.
	#Please note that some mods may not work with a thread count higher than 1. Use with caution.
	#Range: > 1
	computer_threads = 1
	#The ideal maximum time a computer can execute for in a tick, in milliseconds.
	#Note, we will quite possibly go over this limit, as there's no way to tell how long a will take - this aims to be the upper bound of the average time.
	#Range: > 1
	max_main_computer_time = 5

#Controls the HTTP API
[http]
	#The maximum size (in bytes) that a computer can send or receive in one websocket packet.
	#Range: 0 ~ 65536
	max_websocket_message = 65536
	#The number of http requests a computer can make at one time. Additional requests will be queued, and sent when the running requests have finished. Set to 0 for unlimited.
	#Range: > 0
	max_requests = 16
	#The maximum size (in bytes) that a computer can upload in a single request. This includes headers and POST text.
	#Range: > 0
	max_upload = 4194304
	#A list of wildcards for domains or IP ranges that cannot be accessed through the "http" API on Computers.
	#If this is empty then all whitelisted domains will be accessible. Example: "*.github.com" will block access to all subdomains of github.com.
	#You can use domain names ("pastebin.com"), wilcards ("*.pastebin.com") or CIDR notation ("127.0.0.0/8").
	blacklist = ["127.0.0.0/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "fd00::/8"]
	#A list of wildcards for domains or IP ranges that can be accessed through the "http" API on Computers.
	#Set this to "*" to access to the entire internet. Example: "*.pastebin.com" will restrict access to just subdomains of pastebin.com.
	#You can use domain names ("pastebin.com"), wilcards ("*.pastebin.com") or CIDR notation ("127.0.0.0/8").
	whitelist = ["*"]
	#The maximum size (in bytes) that a computer can download in a single request. Note that responses may receive more data than allowed, but this data will not be returned to the client.
	#Range: > 0
	max_download = 16777216
	#The number of websockets a computer can have open at one time. Set to 0 for unlimited.
	#Range: > 1
	max_websockets = 4
	#Enable the "http" API on Computers (see "http_whitelist" and "http_blacklist" for more fine grained control than this)
	enabled = true
	#Enable use of http websockets. This requires the "http_enable" option to also be true.
	websocket_enabled = true
	#The period of time (in milliseconds) to wait before a HTTP request times out. Set to 0 for unlimited.
	#Range: > 0
	timeout = 30000

#Various options relating to peripherals.
[peripheral]
	#The range of Wireless Modems at maximum altitude in clear weather, in meters
	#Range: 0 ~ 100000
	modem_high_altitude_range = 384
	#The range of Wireless Modems at low altitude in stormy weather, in meters
	#Range: 0 ~ 100000
	modem_range_during_storm = 64
	#Enable Command Block peripheral support
	command_block_enabled = false
	#The range of Wireless Modems at maximum altitude in stormy weather, in meters
	#Range: 0 ~ 100000
	modem_high_altitude_range_during_storm = 384
	#The range of Wireless Modems at low altitude in clear weather, in meters
	#Range: 0 ~ 100000
	modem_range = 64
	#Maximum amount of notes a speaker can play at once
	#Range: > 1
	max_notes_per_tick = 8

#Various options relating to turtles.
[turtle]
	#The fuel limit for Advanced Turtles
	#Range: > 0
	advanced_fuel_limit = 100000
	#If set to true, Turtles will be unable to build, dig, or enter protected areas (such as near the server spawn point)
	obey_block_protection = true
	#A list of turtle actions which are disabled.
	disabled_actions = []
	#Set whether Turtles require fuel to move
	need_fuel = true
	#If set to true, Turtles will push entities out of the way instead of stopping if there is space to do so
	can_push = true
	#The fuel limit for Turtles
	#Range: > 0
	normal_fuel_limit = 20000

