
#Discord RichPresence Config File
[Rich-Presence]
	#First line of Rich Presence
	Client-Name = "Forge 1.15"
	#Placeholders:
	#%ip%  Server IP
	Server-Text = "Playing on %ip%"
	#No placeholders supported, Text that shows when you are in the main menu
	Main-Menu = "In Main Menu"
	#Placeholders:
	#%coords% (X:??? Y:??? Z:???)
	#%world% World name
	Singleplayer-Text = "Playing in %world% (%coords%)"
	#Setting this to true disables name changing through GUI
	Disable-Name-changing = false
	#Do you want to use development commands?
	Dev-Commands = false

