
#Nether Ore config for janoeo
[janoeo]
	#Nether diamond ore generation: disable / enable
	netherDiamondOreGen = true
	#Nether gold ore generation: disable / enable
	netherGoldOreGen = true
	#Nether lapis ore generation: disable / enable
	netherLapisOreGen = true
	#Nether iron ore generation: disable / enable
	netherIronOreGen = true
	#Nether dense gold ore generation: disable / enable
	netherDenseGoldOreGen = true
	#Nether emerald ore generation: disable / enable
	netherEmeraldOreGen = true
	#Nether dense redstone ore generation: disable / enable
	netherDenseRedstoneOreGen = true
	#Nether dense coal generation: disable / enable
	netherDenseCoalOreGen = true
	#Nether dense emerald ore generation: disable / enable
	netherDenseEmeraldOreGen = true
	#Nether dense quartz ore generation: disable / enable
	netherDenseQuartzOreGen = true
	#Nether redstone ore generation: disable / enable
	netherRedstoneOreGen = true
	#Nether dense diamond generation: disable / enable
	netherDenseDiamondOreGen = true
	#Nether dense iron ore generation: disable / enable
	netherDenseIronOreGen = true
	#Nether coal ore generation: disable / enable
	netherCoalOreGen = true
	#Nether dense lapis ore generation: disable / enable
	netherDenseLapisOreGen = true

