
#Server configuration settings
[server]
	#Changes if entities are recognized as hostile by other mods. See https://github.com/TeamLapen/Vampirism/issues/199. Smart falls back to Never on servers 
	#Allowed Values: ALWAYS_IMOB, NEVER_IMOB, SMART
	entitiesIMob = "SMART"
	#Block radius the sunscreen beacon affects
	#Range: 1 ~ 40000
	sunscreenBeaconDistance = 32
	#If enabled adds a craftable umbrella that can be used to slowly walk though sunlight without taking damage
	umbrella = false
	#Whether the suncreen beacon can be mined in survival
	sunscreenBeaconMineable = false
	#If PVP should only be allowed between factions. PVP has to be enabled in the server properties for this. Not guaranteed to always protect player from teammates
	pvpOnlyBetweenFactions = false
	#Whether to color player names in chat based on their current faction
	factionColorInChat = true
	#Prevent clients from disabling the vampire forest fog
	enforceForestFog = true
	#Whether glass bottles should be automatically be converted to blood bottles when needed
	autoConvertGlassBottles = true
	#If vampires can convert to a bat in the End
	batModeInEnd = false
	#Percentage of players that have to lay in a coffin to make it night.  Be careful with values below 51 if e.g. Morpheus is installed
	#Range: 1 ~ 100
	coffinSleepPercentage = 100
	#Calculate the blood level for unknown creatures based on their size
	autoCalculateEntityBlood = true
	#Whether players can infect other players
	playersCanTurnPlayers = true

	[server.internal]
		#Send message about Guide-API once
		infoAboutGuideAPI = false

	#Disabling these things might reduce fun or interfere with gameplay
	[server.disable]
		#Prevent vampire mobs from infecting players when attacking
		disableMobBiteInfection = true
		#Disable vampire fangs being usable to infect yourself
		disableFangInfection = false
		#Disable Halloween special event
		disableHalloweenSpecialEvent = false
		#Disable vampire forest generation
		disableVampireForest = false
		#Disable hunter camp generation
		disableHunterTentGen = false

	[server.sundamage]
		#Additional biomes the player should not get sundamage in. Use biome ids e.g. 'minecraft:mesa'
		sundamageDisabledBiomes = []
		#Add the id of any dimension you want to enforce sundamage for to this list. Overrides defaults and values added by other mods
		sundamageDimensionsOverridePositive = []
		#Add the id of any dimension you want to disable sundamage for to this list. Overrides defaults and values added by other mods
		sundamageDimensionsOverrideNegative = []
		#Whether vampires should receive sundamage in unknown dimensions
		sundamageUnknownDimension = false

	[server.cheats]
		#CHEAT: If enabled, you will be able to unlock all skills at max level
		allSkillsAtMaxLevel = false

	[server.village]
		#Village distance
		#Range: 1 ~ 100
		villageDistance = 32
		#Village centers will be at least N chunks apart. Must be smaller than distance
		#Range: 1 ~ 100
		villageSeparation = 8
		#Whether to modify the village world gen (size and frequency)
		villageModify = true

